config/routes.rb
Rails.application.routes.draw do
  resources :robots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy]
  include RobotsHelper
  
  # GET /robots
  # GET /robots.json
  def index
    team_size = 15
    subs = 5
    salary_cap = 175
    team = create_team(team_size, subs, salary_cap)
    @starters = team[0..9]
    @subs = team[10..14]
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
  end

  # GET /robots/new
  def new
    @robot = Robot.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create
    @robot = Robot.new(robot_params)

    respond_to do |format|
      if @robot.save
        format.html { redirect_to @robot, notice: 'Robot was successfully created.' }
        format.json { render :show, status: :created, location: @robot }
      else
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1
  # PATCH/PUT /robots/1.json
  def update
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { redirect_to @robot, notice: 'Robot was successfully updated.' }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :edit }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy
    respond_to do |format|
      format.html { redirect_to robots_url, notice: 'Robot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def robot_params
      params.require(:robot).permit(:name, :speed, :strength, :agility)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
  # The heavy lifting of creating the team of robot warriors
  def create_team(team_size, subs, salary_cap)
    team = []

    (1..team_size).each do |index|
      robot = Robot.new

      # make sure that the robot name is unique
      name = generate_name
      while team.map{|r| r.name}.include? name
        name = generate_name
      end
      robot.name = name

      available_points = generate_available_points(team_size, salary_cap)
      build_attributes(robot, available_points)

      team.push(robot)
    end

    # Remaining points will be added to bots that have duplicates
    remaining_points = calculate_remaining_points(team, salary_cap)

    # Run this until there are no duplicates
    until fix_duplicates(team)
    end

    remaining_points = calculate_remaining_points(team, salary_cap)

    # Return an empty array if we've run out of points, which means we still have a duplicate
    # Hack right now until I think of a better solution for
    return [] if remaining_points < 0

    # Use all remaining points to create a super star
    create_super_star(team.first, remaining_points) if remaining_points > 0
    remaining_points = calculate_remaining_points(team, salary_cap)

    # One more check to make sure we didn't create a duplicate
    # Although thinking about it that'd be impossible since this
    # robot would have more total points than all the others
    return [] if !fix_duplicates(team)

    team
  end

  def generate_name
    alpha = (0...4).map { (65 + rand(26)).chr }.join
    numeric = rand(1000..9999)

    name = alpha + numeric.to_s
  end

  def build_attributes(robot, available_points)
    # dividing initial amount by two for added randomness
    strength = rand(1..available_points) / 2
    strength += 1 if strength == 0
    robot.strength = strength

    # subtract strength from the available points 
    # subtract 1 to ensure there's at least one point left over for speed
    remaining_points = available_points - strength - 1
    agility = rand(1..remaining_points)
    robot.agility = agility

    robot.speed = available_points - robot.strength - robot.agility
  end

  # This number is the max number of points each robot can have
  # IE: If there's 150 available points, each robot can have 10 points
  def generate_available_points(team_size, salary_cap)
    salary_cap/team_size
  end

  def fix_duplicates(team)
    no_duplicates = true
    # Dual each loop to check for duplicates
    team.each_with_index do |robot, index|
      team.drop(index + 1).each do |teammate|
        # add points to teammate so that it gets checked
        if compare_attributes(robot, teammate)
          no_duplicates = false
          # Adding to speed just for sake of ease
          teammate.speed += 1
        end
      end
    end
    no_duplicates
  end

  def compare_attributes(robot, teammate)
    return robot.speed == teammate.speed && robot.strength == teammate.strength && robot.agility == teammate.agility
  end

  # Salary cap minus all the attribute points added up
  def calculate_remaining_points(team, salary_cap)
    salary_cap - team.map{|r| r.speed + r.agility + r.strength}.sum
  end

  # Simply add the rest of the remaining points to a single robot so that we hit the salary cap
  def create_super_star(robot, remaining_points)
    available_attributes = 3
    points_to_add = remaining_points/available_attributes
    robot.agility += points_to_add
    robot.speed += points_to_add
    robot.strength += points_to_add + remaining_points%available_attributes
  end

end

# All this talk of robots got me thinking
# about the best robot of all time
#       _
#      ( )
#       H
#       H
#      _H_ 
#   .-'-.-'-.
#  /         \
# |           |
# |   .-------'._
# |  / /  '.' '. \
# |  \ \ @   @ / / 
# |   '---------'        
# |    _______|  
# |  .'-+-+-+|  
# |  '.-+-+-+|         
# |    """""" |
# '-.______.-'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobotLeague</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/_form.html.erb
<%= form_with(model: robot, local: true) do |form| %>
  <% if robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% robot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :robot_name %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed, id: :robot_speed %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength, id: :robot_strength %>
  </div>

  <div class="field">
    <%= form.label :agility %>
    <%= form.number_field :agility, id: :robot_agility %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing Robot</h1>

<%= render 'form', robot: @robot %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Robots</h1>
<h2>Starters</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speed</th>
      <th>Strength</th>
      <th>Agility</th>
    </tr>
  </thead>

  <tbody>
    <% @starters.each do |robot| %>
      <tr>
        <td><%= robot.name %></td>
        <td><%= robot.speed %></td>
        <td><%= robot.strength %></td>
        <td><%= robot.agility %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h2>Subs</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speed</th>
      <th>Strength</th>
      <th>Agility</th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |robot| %>
      <tr>
        <td><%= robot.name %></td>
        <td><%= robot.speed %></td>
        <td><%= robot.strength %></td>
        <td><%= robot.agility %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/robots/new.html.erb
<h1>New Robot</h1>

<%= render 'form', robot: @robot %>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @robot.name %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @robot.speed %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @robot.strength %>
</p>

<p>
  <strong>Agility:</strong>
  <%= @robot.agility %>
</p>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>